linters:
  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # recommended
    - bodyclose
    - contextcheck
    - cyclop
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - goerr113
    - goimports
    - gomnd
    - gosec
    - loggercheck
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - reassign
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign

    # optional
    # - gocognit
    # - dupl
    # - dupword
    # - durationcheck
    # - gochecknoinits
    # - godot
    # - godox
    # - ireturn
    # - prealloc
    # - wrapcheck

    # tests
    # - ginkgolinter
    - paralleltest
    - tenv
    - testpackage
    - thelper
    - tparallel

    # SQL
    # - execinquery
    # - rowserrcheck
    # - sqlclosecheck

    # tool-specific 
    # - promlinter


run:
  build-tags:
    - integration

skip-dirs:
    - internal/mocks
    