name: lint
on:
  pull_request:
    branches:
        - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
