name: pull-request
on:
  pull_request:
    branches:
        - "main"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout
        uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'

      - name: Download dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -race ./...
